#Docker-Compose File For DEVELOPMENT

version: '3'
services:
  app:
    build:
      context: "."
      dockerfile: "dev.backend.Dockerfile"
    tty: true
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
    working_dir: /app
    environment:
      NODE_ENV: "development"
      DATABASE_URL: postgres://postgres:postgres@db/classroom
    env_file: app.env
    depends_on:
      - db
  db:
    build: 
      context: "."
      dockerfile: "dev.db.Dockerfile"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: classroom
      POSTGRES_HOST: db
      DATABASE_URL: postgres://postgres:postgres@db/classroom