#Docker-Compose File For PRODUCT

version: '3'
services:
  app:
    build:
      context: "."
      dockerfile: "prod.backend.Dockerfile"
    tty: true
    ports:
      - 80:3000
    volumes:
      - ./app:/app
    working_dir: /app
    environment:
      NODE_ENV: "product"