version: 2.1

orbs:
  node: circleci/node@4.4.0
  gcp-cli: circleci/gcp-cli@2.2.0
  heroku: circleci/heroku@1.2.6

jobs:
  test:  
    docker:
      - image: cimg/node:14.17.0
        environment:
          DATABASE_URL: postgres://postgres:postgres@localhost/classroom
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: classroom
    steps:
      - checkout
      - node/install-packages:
          app-dir: app
          pkg-manager: yarn 
      # - run:
      #     name: Run tests
      #     command: npm test
      #     working_directory: /app

  build:  
    docker:
      - image: cimg/node:14.17.0
        environment:
          DATABASE_URL: postgres://postgres:postgres@localhost/classroom
    working_directory	: ~/project/app
    steps:
      - checkout
      - heroku/deploy-via-git:
          branch: main
      - run:
          name: Overwrite env variables
          command: |
            echo "env_variables:" >> app.yaml
            echo "  GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}" >> app.yaml
            echo "  GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}" >> app.yaml
            echo "  SECRET_KEY: ${SECRET_KEY}" >> app.yaml
            echo "  SENDGRID_APIKEY: ${SENDGRID_APIKEY}" >> app.yaml
            echo "  fromemail: ${fromemail}" >> app.yaml
            echo "  reply_to: ${reply_to}" >> app.yaml
      - gcp-cli/initialize
      - run:
          name: Deploy to Google App Engine
          command: |
            gcloud app --quiet deploy app.yaml

workflows:
  build:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only:
                - main