version: 2.1

orbs:
  node: circleci/node@4.4.0
  gcp-cli: circleci/gcp-cli@2.2.0

jobs:
  test:  
    docker:
      - image: cimg/node:14.17.0
        environment:
          DATABASE_URL: postgres://postgres:postgres@localhost/classroom
      - image: circleci/postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: classroom
    steps:
      - checkout
      - node/install-packages:
          app-dir: app
          pkg-manager: yarn 
      # - run:
      #     name: Run tests
      #     command: npm test

  build:  
    docker:
      - image: cimg/node:14.17.0
        environment:
          DATABASE_URL: postgres://postgres:postgres@localhost/classroom
    steps:
      - checkout
      - node/install-packages:
          app-dir: app
          pkg-manager: yarn

workflows:
  build_and_test:
    jobs:
      - test
      - build:
          filters:
            branches:
              only:
                - master